Add noun model
postdict/postdict pull request #18
Opened 2020-09-21 12:19 UTC by Ko001

2020-09-22 03:00 UTC, ryonakano commented
PRありがとうございます!!　辞書になってきました :tada: :raised_hands:

レビューしました。ちょっと修正させていただきました。

- scssの命名がほかのクラスやファイルと一致するように変更しました（ドキュメント化します、すみません :bow: ）
- mockupでvariablesにあった変数たちは、一旦ハードコードに戻して、あとで必要なものだけ再度変数にしようと思います。mockupでむやみやたらに変数を宣言してしまって、結局使ってないものもあったので……
- ページタイトルの一部に、検索した単語が入るように変更
- erbのタグの前後にスペースを追加：`<%end%>`→`<% end %>`など
- p要素の終了タグが一箇所だけ欠落していたのを修正
- Prequizの見出しやクラス名で、each文のindex番号を表示するように変更

（このあとのコメントで、いくつか議論したいことを書きます）

2020-09-22 04:36 UTC, ryonakano commented
議論したい点が2つと、疑問点が1つあります。

## 議論したい点
### 1. 名詞計テーブルの行ごとに新たなモデルを定義してみる
現在、名詞計テーブルは`Noun`という一つのモデルで構成されています。しかし、`id`や`created_at`などの自動挿入されるものを除いたカラム数が35、`show`ビューが624行と、肥大化しているように感じます。ビューでの表示上は1つのテーブルですが、内部的にカラム単位で既存の`Noun`モデルにbelongs_toした新たな`NounColumn`モデルを使用することで、

```erb
<tbody>
  <% @noun.noun_columns.each do |column| %>
    <tr>
      <td>
        <!-- [φ vN]の例文 -->
      </td>
      <td class="center-row"><%= column.noun_form_name %></td> <!-- "__ V"などの名詞形が入る -->
      <td>
        <!-- [φ nN]の例文 -->
      </td>
      <td>
        <!-- [a/the/one's N]の例文 -->
      </td>
      <td>
        <!-- [φ/the/one's Ns]の例文 -->
      </td>
    </tr>
  <% end %>
<tbody>
```

みたいな感じで`each`文を使って書けるのではないでしょうか。

### 2. セルのコンテンツ内でさらにモデルを定義するかどうか
現在、セルのコンテンツ内でさらに`PhraseRouteMeanings``NounPhase``ExampleSetence`モデルが定義されています。変数名を直接画面に出力するとこんな感じですね。

![Screenshot from 2020-09-22 10-51-49](https://user-images.githubusercontent.com/26003928/93843788-0ed0fe80-fcd6-11ea-896c-4486cedfe402.png)

おそらくこれは、モックアップの以下のセルを参考に作られたからだと思います。

![Screenshot from 2020-09-22 13-19-24](https://user-images.githubusercontent.com/26003928/93843846-42ac2400-fcd6-11ea-894a-5f51533f9793.png)

ただ、私は、セルのコンテンツはシンプルな`text`のカラムを定義するに留めるだけでいいのではと思います。（せっかく作ってくださったのにすみません :bowing_woman: ）
なぜなら、例文しかないもの、名詞句しかないもの、名詞句の下に例文がつくもの、セル内で意味がさらに分けられるもの……と、セルによってかなり内容が変わってきます。なので、こちら側でガシッと入れるものを固定してしまうと、このような多様なコンテンツに対応できなくなってしまうのではと思いました。

1. とも関連して、

|キー名|型名|
|--|--|
|vn_cell|text|
|noun_form_name|string|
|nn_none_cell|text|
|nn_singular_cell|text|
|nn_plural_cell|text|

というカラムを持つ`NounColumn`を定義して、`Noun`テーブルにbelongs_toさせるといいのではと思います。

## 疑問点
検索結果画面で、モックアップにあったロゴと検索欄がないのは意図的でしょうか。

2020-09-23 02:37 UTC, Ko001 commented
### １、
なるほど！noun formまでモデルに入れる発想はなかった！
基本的に賛成で、
注意しなきゃいけないこととして、
・必ず全てのnoun formのテーブルが存在すること（initializeでできる？）
・noun form がmockupと同じ順番で並ぶこと
があるのかな？
とすると、noun_form_idもnoun_form_name と対応する形で入っていた方がいいのかなと思った。

### ２、
練習兼ねて、今のような形で作ったんだけど、今のままだと下層のインスタンス（あってる？）を作成するためには上層のインスタンスを作らなきゃいけないっていうめんどくさいことになってるから、シンプルにした方がいいと僕も思う。
一つ疑問は、カラムの中にhtmlタグが入れられるのか、つまり、カラムだけ指定した状態で、セルの中のレイアウトをどうやって変えられるのかなぁとは考えてた。

### 疑問点について
ヘッダーにあたる部分だと思うから、今後なにを増やすかわからないけど、別で分けた方がいいのかもと思って出してあった！

2020-09-24 12:22 UTC, ryonakano commented
> ・必ず全てのnoun formのテーブルが存在すること（initializeでできる？）
> ・noun form がmockupと同じ順番で並ぶこと
> があるのかな？
> とすると、noun_form_idもnoun_form_name と対応する形で入っていた方がいいのかなと思った。

モックアップでの名詞形の順にnewすれば、自動的にその順番で表示されると思います。こんな感じですかね。

```ruby
  def initialize
    noun_form_names = [
      "__ V",
      "__ BE",
      "V __",
      "BE __",
      "P __",
      "there BE __",
      "名詞句のみ"
    ]

    @noun_columns = nil
    noun_form_names.each do |noun_form_name|
      @noun_columns << NounRow.new(noun_form_name: noun_form_name)
    end
  end
```

> 一つ疑問は、カラムの中にhtmlタグが入れられるのか、つまり、カラムだけ指定した状態で、セルの中のレイアウトをどうやって変えられるのかなぁとは考えてた。

私もこれは思いました。ただのtextareaにしてしまうと、書式設定が一切されません。解決策が何かわかりませんが、何らかの方法はあるはずです。ただ、レベルが高いことが予想されます。なので、このPRでは書式付きテキストまでは対応せず、今後方法が分かり次第実装する、という方針でいかがでしょうか。

> ヘッダーにあたる部分だと思うから、今後なにを増やすかわからないけど、別で分けた方がいいのかもと思って出してあった！

そういうことだったのですね。わかりました :+1:

2020-09-29 11:13 UTC, Ko001 commented
反応遅れてごめん！！
方針賛成！明日時間あるからその方向で作ってみるね！

2020-10-02 13:11 UTC, Ko001 reviewed
あ、間違ってた！ごめん！！

2020-10-02 13:26 UTC, ryonakano requested changes
削除したモデルへの変更が記述されていたマイグレーションファイルの削除（`rails d`コマンドでは、createマイグレーションファイルしか削除してくれないそうです。[参照元](https://qiita.com/YujiNaito/items/b6f6ef89f7b60309d5b1#%E6%B3%A8%E6%84%8F%E7%82%B9)）と、変数名の修正をしました。

辛口レビューかもしれません…… 🌶

2020-10-02 13:26 UTC, ryonakano commented on app/views/search/show.html.erb
> +          <% end%>
```suggestion
          <% @noun_rows.each do |noun_row| %>
            <tr>
              <td><%= noun_row.vn_cell %></td> <%# φ vNの列 %>
              <td class="center-row"><%= noun_row.noun_form_name %></td>
              <td><%= noun_row.nn_none_cell %></td> <%# φ nNの列 %>
              <td><%= noun_row.nn_singular_cell %></td> <%# a/the/one's nNの列 %>
              <td><%= noun_row.nn_plural_cell %></td> <%# a/the/one's nNsの列 %>
            </tr>
          <% end %>
```

- 細かいことなのですが、erbの閉じタグの前に半角スペースを一つ入れてください。
- 変数名をコメントに書いても、それが何の変数なのかは直感的にわからないと思います。コメントを残すのであれば、その変数の説明になるような文章を書いた方がいいと思います。

2020-10-02 13:26 UTC, ryonakano commented on app/views/search/index.html.erb
> +<% @nouns.each do |noun|%>
```suggestion
<% @nouns.each do |noun| %>
```

2020-10-02 13:26 UTC, ryonakano commented on app/views/search/index.html.erb
> +<% end%>
```suggestion
<% end %>
```

2020-10-02 13:26 UTC, ryonakano commented on app/controllers/search_controller.rb
> +  end
```suggestion
```

現時点ではcreateアクションを使うビューはないので、このPRではこの変更はまだ加えないほうがいいと思います。

2020-10-02 13:42 UTC, Ko001 commented
色々と足引っ張ってしまって申し訳ない🙇‍♂️
気をつけます、、、

2020-10-03 00:10 UTC, ryonakano reviewed
Just one tiny thing, otherwise LGTM.

2020-10-03 00:11 UTC, ryonakano reviewed
Just one thing, otherwise LGTM.

2020-10-03 00:11 UTC, ryonakano commented on db/schema.rb
> +  end
このテーブル`nnouns`は、どのように使う目的で追加されたものでしょうか。現時点でのコードで使われていない気がするのですが……

2020-10-03 05:39 UTC, Ko001 commented on db/schema.rb
> +  end
ごめん、消したはずなんだけど消えてないだけ！🙇‍♂️

2020-10-03 06:19 UTC, ryonakano commented on app/views/search/index.html.erb
> +<% end%>
```suggestion
<% end %>
```

2020-10-03 06:21 UTC, ryonakano approved these changes

2020-10-03 06:21 UTC, merged