Table settings
postdict/postdict pull request #44
Opened 2020-10-20 04:23 UTC by Ko001

- add seed datta
- set has_many to noun model and belongs_to relations to quiz model

2020-10-20 11:29 UTC, ryonakano requested changes
I guess you shouldn't remove these files:

* app/assets/stylesheets/search.scss
* app/javascript/packs/application.js
* app/views/search/show.html.erb

2020-10-25 02:43 UTC, Ko001 commented
Thanks for your PR.
It was totally an accident.  I didn't mean to do this, my apologies.
I restored those files.

2020-10-26 03:57 UTC, ryonakano reviewed
I don't think adding `db/migrate/20201022035429_add_alt_answer_to_quiz_table.rb` is not related to this PR. I guess you'd like to add columns for alternative answers but it would be better to create another PR for this.

Keeping unrelated things out makes PRs smaller, cleaner, and easier to revert in the future if needed.

2020-10-26 04:00 UTC, Ko001 commented
Well, you are absolutely correct.  I somehow messed up this branch and add-js-for-quizzes.  The file is for answer check function.

2020-10-26 04:26 UTC, Ko001 commented
Please forget about my deleted comment.
I understand your point.  However, the file seems necessary to me, though I'm not sure if we have to add it to this PR.

Currently, the answer for the last post quiz is like this below.
`Quiz.create(original_noun: 'sale', sentence_jp: 'シャロンはセールで安く選んだとてもすてきな家具をもっている。', sentence_en: 'Sharon has some really nice furniture she picked up cheap in ( sale ).', placeholder: 'sale', answer: 'a [the] sale', kind: 'post')`

It has two answers but only one answer column on the table.  It has made me think of adding alternative answers column on this branch and changing answer check function in accordance with it.
I know I'm sort of messing up this branch and add-js-for-quizzes branch, so I wanna have your opinion, again.

2020-10-26 05:16 UTC, ryonakano commented
Ah now I see the problem and the reason why you added it… but it would be another issue and better to fix in another PR. I opened an issue for that (#45) so we may want to revert adding this file

2020-10-26 07:03 UTC, Ko001 commented
100% agree.  And sorry again, I made a mess.  I just learned how to revert...

2020-10-26 12:37 UTC, ryonakano commented
Two concerns I have:

- is it OK to quote example sentences in some dictionaries without credit?—maybe not.
- also, suppose we credit, is it OK to use these dictionaries like this? I mean, some dictionaries may only allow for personal use like just checking words meanings or quoting the contents in our reports and forbid publicizing quoted contents.

We may want to ask Hikky about these thing.

2020-10-27 16:46 UTC, Ko001 commented
100% agree, we need to ask him.

It might be possible to claim this dictionary is a part of his research and that the best way to show word categorization, though we may have to delete quizzes.
It's just a ramdom thougt.

2020-11-08 13:10 UTC, ryonakano requested changes
Sorry for the late review! (FYI I modified your PR to unify the use of `"` and `'` :wink:)

After some testing with this branch, I suppose we don't need the following changes to the models. I got the following errors when I try to create a new Quiz instance:

```ruby
@messages={:nouns=>["must exist"]}, @details={:nouns=>[{:error=>:blank}]}>
```

Removing these two lines creates a new pre/post quiz successfully.

2020-11-08 13:10 UTC, ryonakano commented on app/models/quiz.rb
> +  belongs_to :nouns
```suggestion
```

2020-11-08 13:10 UTC, ryonakano commented on app/models/noun.rb
> +  has_many :quizzes, dependent: :destroy
```suggestion
```

2020-12-26 12:33 UTC, ryonakano approved these changes
Works fine.

2020-12-26 12:34 UTC, merged